version: '2'
services:
  toa_postgres:
    image: postgres
    container_name: tezos_cso_postgres
    ports:
     - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}